spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.92.23.92:3306/madpill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: madpill
    password: ENC(ypVxSulVJlDmkk4nO6kGLeC3XnDljnNX)


