spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.92.23.92:3306/madpill_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: madpill
mybatis:
  config-location: classpath:mybatis-config.xml
