spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.92.23.92:3306/madpill_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: madpill
    password: ENC(ypVxSulVJlDmkk4nO6kGLeC3XnDljnNX)
    initialization-mode: always
    schema: classpath:sql/schema.sql
    data: classpath:sql/madpill_test.sql
