spring:
  datasource:
    url: jdbc:mysql://${mysql-ip:localhost}:3306/${mysql-database:madpill_test}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: ${mysql-username}
    password: ${mysql-password}