spring:
  datasource:
    url: jdbc:mysql://${mysql-ip:34:92:23:92}:3306/${mysql-database:madpill}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: ${mysql-username:madpill}
    password: ${mysql-password:ENC(ypVxSulVJlDmkk4nO6kGLeC3XnDljnNX)}